name       : tilda
version    : 1.5.2
release    : 13
source     :
    - https://github.com/lanoxx/tilda/archive/tilda-1.5.2.tar.gz : 3d6b9ea01d39692685e410f365c64ed63b604372e4e4f82b99e82c4967ef03db
license    : GPL-2.0-only
summary    : Tilda Terminal Emulator
component  : system.utils
description: |
    Tilda is a terminal emulator and can be compared with other popular terminal emulators such as gnome-terminal (Gnome), Konsole (KDE), xterm and many others. The specialities of Tilda are that it does not behave like a normal window but instead it can be pulled up and down from the top of the screen with a special hotkey. Additionally Tilda is highly configurable. It is possible to configure the hotkeys for keybindings, change the appearance and many options that affect the behavior of Tilda.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libconfuse)
    - pkgconfig(vte-2.91)
setup      : |
    %autogen --enable-lto --disable-maintainer-mode
build      : |
    %make
install    : |
    %make_install
