name       : tilda
version    : 1.3.3
release    : 5
source     :
    - https://github.com/lanoxx/tilda/archive/tilda-1.3.3.tar.gz : 71baa5572c498e5b3e94f5b57e8118c1ef0fdaea269a5b2425208e1adec284b1
license    : GPL-2.0
summary    : Tilda Terminal Emulator
component  : system.utils
description: |
    Tilda is a terminal emulator and can be compared with other popular terminal emulators such as gnome-terminal (Gnome), Konsole (KDE), xterm and many others. The specialities of Tilda are that it does not behave like a normal window but instead it can be pulled up and down from the top of the screen with a special hotkey. Additionally Tilda is highly configurable. It is possible to configure the hotkeys for keybindings, change the appearance and many options that affect the behavior of Tilda.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(libconfuse)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
