name       : tilda
version    : 1.5.4
release    : 15
source     :
    - https://github.com/lanoxx/tilda/archive/tilda-1.5.4.tar.gz : c9528b0e9af6f5a35db9ca695b3edbb6709755e82afdfc3cdb75a406ddc67523
license    : GPL-2.0-only
summary    : Tilda Terminal Emulator
component  : system.utils
description: |
    Tilda is a terminal emulator and can be compared with other popular terminal emulators such as gnome-terminal (Gnome), Konsole (KDE), xterm and many others. The specialities of Tilda are that it does not behave like a normal window but instead it can be pulled up and down from the top of the screen with a special hotkey. Additionally Tilda is highly configurable. It is possible to configure the hotkeys for keybindings, change the appearance and many options that affect the behavior of Tilda.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libconfuse)
    - pkgconfig(vte-2.91)
setup      : |
    %autogen --enable-lto --disable-maintainer-mode
build      : |
    %make
install    : |
    %make_install
